volumes:
  pgdata:

services:
  db:
    container_name: aristadb
    hostname: aristadb
    ports:
      - 5433:5432
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE:-arista}
      PGDATA: /var/lib/postgresql/data/arista
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
    - digital-lions_postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    networks:
      - digital-lions_postgres 

# using network from other side project such 
# that I can use the same pgadmin instance for both servers
networks:
  digital-lions_postgres:
    external: true
