# config that contains which pairs to maintain in database
# see https://docs.coinglass.com/reference/instruments

fundingRate:
  symbols:
    - BTCUSDT
    - ETHUSDT
    - SOLUSDT
    - XRPUSDT
    - BNBUSDT
    - DOGEUSDT
    - TONUSDT
    - 1000PEPEUSDT
    - LTCUSDT
openInterest:
  symbols:
    - BTCUSDT
    - ETHUSDT
    - SOLUSDT
    - XRPUSDT
    - BNBUSDT
    - DOGEUSDT
    - TONUSDT
    - 1000PEPEUSDT
    - LTCUSDT

