# config that contains which pairs to maintain in database
# see https://docs.coinglass.com/reference/instruments
# each table should have an exisitng repository

funding_rate:
  binance:
    - BTCUSDT
    - ETHUSDT
    - SOLUSDT
    - XRPUSDT
    - BNBUSDT
    - DOGEUSDT
    - TONUSDT
    - 1000PEPEUSDT
    - LTCUSDT
open_interest:
  binance:



