"""Remove unique constriant

Revision ID: 13c25ade546b
Revises: 0484ece0decb
Create Date: 2024-11-06 16:22:03.791739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "13c25ade546b"
down_revision: Union[str, None] = "0484ece0decb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "instrument_time_unique_constraint", "deribit_futures", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "instrument_time_unique_constraint",
        "deribit_futures",
        ["instrument", "datetime_"],
    )
    # ### end Alembic commands ###
