"""Add deribit future table

Revision ID: 8da2daa87275
Revises: c98da7da90d0
Create Date: 2024-11-05 23:01:17.679730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8da2daa87275"
down_revision: Union[str, None] = "c98da7da90d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deribit_futures",
        sa.Column("asset", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instrument", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "future_reference", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("expiration", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("unix_timestamp", sa.Integer(), nullable=False),
        sa.Column("datetime_", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deribit_futures")
    # ### end Alembic commands ###
