"""Add ISO col

Revision ID: 792e01babb51
Revises: bc6304c73727
Create Date: 2024-10-18 10:45:24.976365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "792e01babb51"
down_revision: Union[str, None] = "bc6304c73727"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "coin_market_cap",
        sa.Column("iso_date", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coin_market_cap", "iso_date")
    # ### end Alembic commands ###
