"""Add OpenInterest table

Revision ID: 4fa1ae8b0448
Revises: 792e01babb51
Create Date: 2024-10-24 14:34:41.683145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4fa1ae8b0448"
down_revision: Union[str, None] = "792e01babb51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "openinterest",
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("open_interest", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("utc", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol", "timestamp", "utc", name="symbol_time_unique_constraint"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("openinterest")
    # ### end Alembic commands ###
