"""Add unique constraint

Revision ID: 0484ece0decb
Revises: 8da2daa87275
Create Date: 2024-11-05 23:07:05.834885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '0484ece0decb'
down_revision: Union[str, None] = '8da2daa87275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('instrument_time_unique_constraint', 'deribit_futures', ['instrument', 'datetime_'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('instrument_time_unique_constraint', 'deribit_futures', type_='unique')
    # ### end Alembic commands ###
