"""Rename column

Revision ID: a03a1e549978
Revises: d26f0e83c759
Create Date: 2024-10-25 09:04:35.881277

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a03a1e549978"
down_revision: Union[str, None] = "d26f0e83c759"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "oi_symbol_time_unique_constraint", "open_interest", type_="unique"
    )
    op.alter_column(
        "open_interest", "timestamp", nullable=False, new_column_name="unix_timestamp"
    )
    op.create_unique_constraint(
        "oi_symbol_time_unique_constraint",
        "open_interest",
        ["symbol", "unix_timestamp", "utc"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "oi_symbol_time_unique_constraint", "open_interest", type_="unique"
    )
    op.alter_column(
        "open_interest", "unix_timestamp", nullable=False, new_column_name="timestamp"
    )
    op.create_unique_constraint(
        "oi_symbol_time_unique_constraint",
        "open_interest",
        ["symbol", "timestamp", "utc"],
    )
    # ### end Alembic commands ###
