"""Restructure tables

Revision ID: d26f0e83c759
Revises: 4fa1ae8b0448
Create Date: 2024-10-24 14:51:52.600233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd26f0e83c759'
down_revision: Union[str, None] = '4fa1ae8b0448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_rate',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aggregated_funding_rate', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('utc', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', 'utc', name='fr_symbol_time_unique_constraint')
    )
    op.create_table('open_interest',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aggregated_open_interest', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('utc', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', 'utc', name='oi_symbol_time_unique_constraint')
    )
    op.drop_table('openinterest')
    op.drop_table('ohlc_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlc_history',
    sa.Column('exchange', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('coinglass_future', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('o', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('h', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('l', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('t', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interval', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ohlc_history_pkey')
    )
    op.create_table('openinterest',
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('open_interest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='openinterest_pkey'),
    sa.UniqueConstraint('symbol', 'timestamp', 'utc', name='symbol_time_unique_constraint')
    )
    op.drop_table('open_interest')
    op.drop_table('funding_rate')
    # ### end Alembic commands ###
