"""Add change interval type

Revision ID: 46b0c793fa65
Revises: 56dd70ab525b
Create Date: 2024-07-30 07:24:48.068829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '46b0c793fa65'
down_revision: Union[str, None] = '56dd70ab525b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funding_rates', 'interval',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funding_rates', 'interval',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
