"""Add interval column

Revision ID: 56dd70ab525b
Revises: 40618842fa23
Create Date: 2024-07-30 07:21:01.806099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '56dd70ab525b'
down_revision: Union[str, None] = '40618842fa23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funding_rates', sa.Column('interval', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funding_rates', 'interval')
    # ### end Alembic commands ###
