"""Add datetime col?


Revision ID: 5caa0d9a71f8
Revises: 21067b772840
Create Date: 2024-08-13 15:49:34.603480

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5caa0d9a71f8"
down_revision: Union[str, None] = "21067b772840"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("funding_rates", sa.Column("utc", sa.DateTime(), nullable=False))
    op.alter_column(
        "funding_rates",
        "t",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "funding_rates",
        "t",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.drop_column("funding_rates", "utc")
    # ### end Alembic commands ###
