"""Add Coinmarketcap table

Revision ID: c2c23aa49fc5
Revises: c1ea072719e9
Create Date: 2024-10-16 08:31:29.492977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c2c23aa49fc5'
down_revision: Union[str, None] = 'c1ea072719e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_market_cap',
    sa.Column('cmc_rank', sa.Integer(), nullable=False),
    sa.Column('cmc_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_cap_by_total_supply', sa.Float(), nullable=False),
    sa.Column('circulating_supply', sa.Float(), nullable=False),
    sa.Column('total_supply', sa.Float(), nullable=False),
    sa.Column('max_supply', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume_24h', sa.Float(), nullable=False),
    sa.Column('volume_change_24h', sa.Float(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=False),
    sa.Column('fully_diluted_market_cap', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('utc', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coin_market_cap')
    # ### end Alembic commands ###
