name: Fetch and insert CoinMarketCap latest

on:
  schedule:
  # Coinglass API interval is 4h so we update 10 minutes after each interval
  - cron: 0 */4 * * *
  push:

jobs:
  sync:
    name: Populate Database
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Python version
      run: |
        PYTHON_VERSION=$(cat .python-version)
        echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV
    - name: Set Poetry version
      run: |
        POETRY_VERSION=$(cat .poetry-version)
        echo "POETRY_VERSION=$POETRY_VERSION" >> $GITHUB_ENV
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install Poetry
      run: |
        pip install poetry==${{ env.POETRY_VERSION }}
    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root
    - name: Run script
      shell: bash
      env:
        COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
        POSTGRES_DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
      run: |
        poetry run sync_cmc
