name: Fetch Coinglass 8hr funding rate

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decode Google Service credentials to file
        run: |
          echo ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }} | base64 --decode >> service-account-file.json
      - name: Install Poetry
        run: |
          pip install poetry==$(cat .poetry-version)
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Run script
        shell: bash
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service-account-file.json
          COINGLASS_API_KEY: ${{ secrets.COINGLASS_API_KEY }}
          SPREADSHEET_ID: ${{ vars.SPREADSHEET_ID }}
        run: |
          poetry run google

