name: Fetch Coinglass 8hr funding rate

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: $(cat .python-version}
      - name: Install Poetry
        run: |
          pip install poetry==$(cat .poetry-version)
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Run script
        shell: bash
        env:
          COINGLASS_API_KEY: ${{ secrets.COINGLASS_API_KEY }}
          POSTGRES_DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
        run: |
          poetry run python arista/main.py
